#!/usr/bin/env bash
# vim: set ft=sh sw=2 et

set -euf -o pipefail

export GOARCH
GOARCH=$(go env GOARCH 2>/dev/null || echo "amd64")

export CNI_PATH=/opt/cni/bin

os::install_ignite() {
  local VERSION=v0.10.0

  gh::download "weaveworks/ignite" "${VERSION}" "ignite-${GOARCH}" "/usr/local/bin/ignite"
  gh::download "weaveworks/ignite" "${VERSION}" "ignited-${GOARCH}" "/usr/local/bin/ignited"
}

os::install_ignite
