#!/bin/bash
# vim: set ft=sh sw=2:


nvim::venvs() {
  if [ ! -d "${HOME}/.config/nvim/py3" ]; then
    python3 -m venv "${HOME}/.config/nvim/py3"
  fi

  "${HOME}/.config/nvim/py3/bin/python" -m ensurepip --upgrade
  "${HOME}/.config/nvim/py3/bin/pip3" install --upgrade pip neovim
}

nvim::plug_installed() {
  # install vim-plug if not installed
  if [ ! -e "$HOME"/.vim/autoload/plug.vim ]; then
    curl -fLo "$HOME"/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  fi
}

nvim::update_plugins() {
  nvim +PlugInstall +PlugUpdate +PlugClean! +qa
}

nvim::ensure() {
  mkdir -p "${HOME}/.config/nvim"
  nvim::venvs
  nvim::plug_installed
  nvim::update_plugins
}

nvim::ensure
