#!/bin/bash

# vim: set ft=sh sw=2:

export GOARCH=$(go env GOARCH 2>/dev/null || echo "amd64")

_ROOT="$(dirname "${BASH_SOURCE}")/.."

# . "${_ROOT}/hooks/os"

log::f () {
 printf "INFO: %s $*\n" "$(date)"
}

log::e () {
  printf "ERROR: %s  $*\n" "$(date)"
}

os::install_pip() {
  log::f "Installing pip"

  local out
  out="$(mktemp)"

  log::f "Installing Pip"

  curl -LO "$out" https://bootstrap.pypa.io/get-pip.py
  python "$out"
}

os::get_distro() {
  # Determine OS platform
  UNAME=$(uname | tr "[:upper:]" "[:lower:]")

  # If Linux, try to determine specific distribution
  if [ "$UNAME" == "linux" ]; then
    # If available, use LSB to identify distribution
    if [ -f /etc/lsb-release -o -d /etc/lsb-release.d ]; then
      export DISTRO=$(lsb_release -i | cut -d: -f2 | sed s/'^\t'//)
    # Otherwise, use release info file
    else
      export DISTRO=$(ls -d /etc/[A-Za-z]*[_-][rv]e[lr]* | grep -v "lsb" | cut -d'/' -f3 | cut -d'-' -f1 | cut -d'_' -f1)
    fi
  fi

  # For everything else (or if above failed), just use generic identifier
  [ "$DISTRO" == "" ] && export DISTRO=$UNAME
  unset UNAME
}

kube::binaries() {
  curl -L -o "$HOME/bin/kubectl" "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
  ## TODO: Secure me
  curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
}

os::ubuntu::install_packages() {
  log::f "Installing apt packages"

  sudo apt update

  sudo apt install -y --no-install-recommends \
    binutils                   \
    containerd                 \
    cpu-checker                \
    curl                       \
    dmsetup                    \
    fonts-firacode             \
    fzf                        \
    gawk                       \
    git                        \
    gnupg                      \
    neovim                     \
    nodejs                     \
    npm                        \
    openssh-client             \
    ppa-purge                  \
    python2                    \
    python2-setuptools-whl     \
    python3-neovim             \
    python3-venv               \
    ruby                       \
    silversearcher-ag          \
    software-properties-common \
    tmux                       \
    virtualenv                 \
    xclip                      \
    zsh

  log::f "Installing snap packages"
  sudo snap install --edge starship
}

os::set_zoom_scaling_factor () {
  perl -i -pe 's/scaleFactor=2/scaleFactor=1/' ~/.config/zoomus.conf
}

go::install_developer_tools() {
  sudo snap install go --classic
  go get -u github.com/goware/modvendor
  go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.52.2
}

os::install_pip
pip3 install --user -r "${_ROOT}/requirements.txt"


# Tools
#######

go::install_developer_tools
tools::install_terraform() {
  wget -O- https://apt.releases.hashicorp.com/gpg | \
  gpg --dearmor | \
  sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg

  echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] \
https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
  sudo tee /etc/apt/sources.list.d/hashicorp.list
  sudo apt update
  sudo apt install -y terraform
}

tools::install_ansible() {
  sudo apt-add-repository -y ppa:ansible/ansible
  sudo apt update
  sudo apt install -y ansible
}

tools::install_vegeta() {
  go install github.com/tsenart/vegeta@latest
}

tools::install_terraform
tools::install_ansible
tools::install_vegeta

# TODO:
# - Wireshark
# - SSLScan (https://github.com/ioerror/sslscan)

