[tools]
neovim = "0.11.6"
starship = "1.24.2"
atuin = "18.13.3"
doctl = "1.152.0"
kubectl = "1.35.3"
vale = "3.14.1"
helm = "4.1.3"
kubebuilder = "4.13.0"
"pipx:autopep8" = "2.3.2"
"pipx:awscli" = "1.44.63"
"pipx:black" = "latest"
"pipx:esptool" = "latest"
"pipx:isort" = "latest"
"pipx:mypy" = "latest"
"nerdctl" = "2.2.1"
"pipx:oci-cli" = "3.76.1"
"regctl" = "0.11.2"
"pipx:ruff" = "latest"
"github:tsenart/vegeta" = "v12.13.0"
